---
# roles/redis-sentinel/tasks/ssl.yml
# generate ssl/tls certificate

#ca certificate

- name: create directory for ssl files
  file:
    path: /etc/redis/tls
    state: directory
    owner: redis
    group: redis
    mode: '0755'

- name: generate ca passphrase
  set_fact:
    ca_password: "{{ lookup('password', '/dev/null length=25 chars=ascii_letters,digits,punctuation') }}"
  run_once: true
  delegate_to: "{{ groups['redis_primary'][0] }}"

- name: generate ca key
  community.crypto.openssl_privatekey_pipe:
    passphrase: '{{ ca_password }}'
    cipher: auto
  register: ca_key
  run_once: true
  delegate_to: "{{ groups['redis_primary'][0] }}"

- name: generate ca csr
  community.crypto.openssl_csr_pipe:
    privatekey_content: '{{ ca_key.privatekey }}'
    privatekey_passphrase: '{{ ca_password }}'
    country_name: '{{ country_name }}'
    state_or_province_name: '{{ state_or_province_name }}'
    locality_name: '{{ locality_name }}'
    organization_name: '{{ organization_name }}'
    email_address: '{{ email_address }}'
    common_name: '{{ ca_common_name }}'
    use_common_name_for_san: false
    basic_constraints:
      - 'CA:TRUE'
    basic_constraints_critical: yes
    key_usage:
      - keyCertSign
    key_usage_critical: true
  register: ca_csr
  run_once: true
  delegate_to: "{{ groups['redis_primary'][0] }}"

- name: generate ca crt
  community.crypto.x509_certificate:
    path: '{{ redis_cacert }}'
    privatekey_content: '{{ ca_key.privatekey }}'
    privatekey_passphrase: '{{ ca_password }}'
    csr_content: '{{ ca_csr.csr }}'
    selfsigned_not_after: +3650d
    provider: selfsigned
    owner: redis
    group: redis
    mode: '0640'

#server certitificate

- name: generate server key
  community.crypto.openssl_privatekey:
    path: '{{ redis_key }}'
    return_content: yes
    owner: redis
    group: redis
    mode: '0640'
  no_log: true
  register: server_key

- name: generate server csr
  community.crypto.openssl_csr_pipe:
    privatekey_path: '{{ redis_key }}'
    country_name: '{{ country_name }}'
    state_or_province_name: '{{ state_or_province_name }}'
    locality_name: '{{ locality_name }}'
    organization_name: '{{ organization_name }}'
    email_address: '{{ email_address }}'
    common_name: '{{ common_name }}'
    use_common_name_for_san: false
  register: server_csr

- name: generate server cert signed with ca cert
  community.crypto.x509_certificate:
    path: '{{ redis_cert }}'
    return_content: yes
    privatekey_path: '{{ redis_key }}'
    csr_content: '{{ server_csr.csr }}'
    ownca_path: '{{ redis_cacert }}'
    ownca_privatekey_content: '{{ ca_key.privatekey }}'
    ownca_privatekey_passphrase: '{{ ca_password }}'
    ownca_not_after: +3650d
    provider: ownca
    owner: redis
    group: redis
    mode: '0640'
  register: server_crt

- name: generate DH params
  community.crypto.openssl_dhparam:
    path: '{{ redis_dh }}'
    size: 2048
    owner: redis
    group: redis
    mode: '0640'

- name: clear varibles
  set_fact:
    ca_crt: ''
    ca_csr: ''
    ca_key: ''
    server_crt: ''
    server_csr: ''
    server_key: ''