# linode redis-sentinel ansible playbook

# linodes
- name: configure redis-sentinel cluster
  hosts: all
  any_errors_fatal: true
  user: root
  vars:
    local_home: "{{ lookup('env','HOME') }}"
  vars_files:
    - group_vars/redis-sentinel/vars
    - group_vars/redis-sentinel/secret_vars
  
  roles:
    - common      
    - redis-sentinel
    - post